name: Multi Arch Docker Build

on:
  push:

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  PROGRESS_NO_TRUNC: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Allow us to build multi-arch images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Do the build
        run: docker buildx build --platform linux/arm64/v8,linux/amd64 .
